### ISSUE TITLE
Make docs

### ISSUE THREAD

**Issue by jacc** [cappuccino-js/cappuccino.js#1]
idk what happened but going to the site displays a blank page prolly should fix tht

**Comment by jacc** [comment]
i thought i fixed it but i guess nit

**Comment by professor-cat** [comment]
github doesn't do instant website build for each commit so it takes time (around 20 mins)

**Comment by jacc** [comment]
oof

**Comment by professor-cat** [comment]
oh i see what you meant 👀 
docs didn't show any buttons to real API docs not frontpage

**Comment by jacc** [comment]
i was talking about docma

**Comment by professor-cat** [comment]
Me too thanks

Also I won’t be using docma or any other website pre-generator for docs

**Comment by jacc** [comment]
why? docma is op as hecc

**Comment by professor-cat** [comment]
I know myself but it isn’t what I need

**Comment by jacc** [comment]
so manual doccs?

**Comment by professor-cat** [comment]
Nope just website is mine not docs

Docs will be generated by any docs engine and website will parse it

**Comment by jacc** [comment]
so what engine will we use to generate it bc i can do doc stuff but the frontend code might be a little weird for me

**Comment by jacc** [comment]
ill do my best tho

**Comment by professor-cat** [comment]
i am planning to use just riotjs and fetch API
docs.json will be fetched from github or npm build

**Comment by jacc** [comment]
okie

**Comment by professor-cat** [comment]
lets move this [here](https://github.com/orgs/cappuccino-js/teams/great-animals/discussions/2)
